### ISSUE TITLE
invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by zhangsong1213** [yxxxxxxxx/CrowdCountingLabelTool#1]
i run this code  get this result:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\11486\Anaconda3\envs\AA\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "<ipython-input-16-3bc92f25322a>", line 263, in loadDir
    self.category = int(s)
ValueError: invalid literal for int() with base 10: 'C:\\Users\\11486\\Desktop\\label\\a1'

**Comment by zhicai-liu** [comment]
> i run this code get this result:
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\11486\Anaconda3\envs\AA\lib\tkinter__init__.py", line 1702, in **call**
> return self.func(*args)
> File "", line 263, in loadDir
> self.category = int(s)
> ValueError: invalid literal for int() with base 10: 'C:\Users\11486\Desktop\label\a1'

I encountered the same problem
